Skip pull-request-build on master push (#6934)
The runs pushes to master always fail because PR_NUMBER is absent, so
the script invocation fails:

[2026-05-01T17:28:57.403Z] --pr-number value is required!
Error: Process completed with exit code 1.

Running this on master push is redunant anyway because PR's go through
the merge queue first, where this script *does* run correctly.